services:
  postgres:
    image: postgres:17
    container_name: opencircle-postgres
    environment:
      POSTGRES_DB: opencircle_db
      POSTGRES_USER: opencircle
      POSTGRES_PASSWORD: opencircle
    ports:
      - "5434:5432"
    volumes:
      - opencircle_postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:v1.27
    container_name: opencircle-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  opencircle_postgres_data: