spring.application.name=open-circle-api

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.security.jwt.expiration-minutes=60

app.cors.allowed-origins=http://localhost:5173