spring.application.name=open-circle-api

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.security.jwt.expiration-minutes=60

app.cors.allowed-origins=http://localhost:5173

app.mail.from=no-reply@opencircle.local
app.verification.email.code-expiration-minutes=15
app.verification.email.max-attempts=5